In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn import cluster
from sklearn import ensemble
from sklearn import cross_validation
from sklearn.metrics import roc_auc_score as auc
import time

C:\Users\shubham\Anaconda3\lib\site-packages\sklearn\utils\fixes.py:64: DeprecationWarning: inspect.getargspec() is deprecated, use inspect.signature() instead
  if 'order' in inspect.getargspec(np.copy)[0]:

In [3]:
train = pd.read_csv('train.csv/train.csv')
test = pd.read_csv('test/test.csv')

In [5]:
plt.rcParams['figure.figsize'] = (10,10)

In [7]:
##Remove columns with zero standard deviation
zero_std_col = []
for column in train.columns:
    if train[column].std()==0:
        zero_std_col.append(column)

train.drop(zero_std_col,axis=1,inplace=True)

In [26]:
##Remove identical columns
col_identical_col = []
for i in range(0,len(train.columns)-1):
    for j in range(i+1,len(train.columns)):
        if np.array_equal(train[train.columns[i]].values,train[train.columns[j]].values)==True:
            col_identical_col.append(i)


col_to_remove = []
[col_to_remove.append(train.columns[i]) for i in col_identical_col]
train.drop(col_to_remove,axis=1,inplace=True)

In [36]:
trainlabels = train['TARGET']
trainfeatures = train.drop(['ID','TARGET'],axis=1)

In [51]:
from sklearn.cross_validation import train_test_split
from sklearn.metrics import auc
from sklearn.ensemble import gradient_boosting

In [102]:
gbm_classifier = ensemble.GradientBoostingClassifier(n_estimators=20,max_features=1,max_depth=3,min_samples_leaf=100
                                                            ,subsample=0.65,learning_rate=0.1,loss='deviance',random_state=1)

In [38]:
x_train,x_valid,y_train,y_valid = train_test_split(trainfeatures,trainlabels,test_size=0.5,random_state=1)

nan

In [103]:
featuretable = pd.DataFrame(index=range(len(x_train.columns)),columns=['Feature','AUC'])
for i,feature in enumerate(x_train.columns):
    traininputfeature = x_train[feature].values.reshape(-1,1)
    validinputfeature = x_valid[feature].values.reshape(-1,1)
    gbm_classifier.fit(traininputfeature,y_train)
    valid_auc = auc(y_valid,gbm_classifier.predict_proba(validinputfeature)[:,1],reorder=True)
    featuretable.ix[i,'Feature'] = feature
    featuretable.ix[i,'AUC'] = valid_auc

In [142]:
featuretable.sort_values(by='AUC',axis=0,ascending=False).reset_index(drop=True)

                           Feature        AUC
0                       saldo_var8   0.107301
1            saldo_medio_var8_ult1  0.0939473
2          imp_op_var39_efect_ult3  0.0930698
3          imp_op_var41_efect_ult3  0.0902497
4                imp_op_var41_ult1  0.0901898
5                imp_op_var39_ult1  0.0883527
6           saldo_medio_var8_hace2  0.0846721
7          imp_op_var39_efect_ult1   0.084081
8          imp_op_var41_efect_ult1  0.0790844
9            saldo_medio_var8_ult3  0.0761681
10                  num_var22_ult1  0.0697507
11                     saldo_var25  0.0689002
12                     saldo_var26  0.0674973
13               num_op_var39_ult1   0.064028
14                      saldo_var1   0.063838
15         num_op_var39_comer_ult1  0.0634408
16                     saldo_var42  0.0625638
17                        num_var1  0.0620878
18                        ind_var1  0.0620878
19                     saldo_var30  0.0612557
20         num_op_var39_efect_ult3  0.0608291
21                      saldo_var5  0.0608231
22         num_op_var41_comer_ult1  0.0606853
23                     saldo_var40  0.0602931
24                       num_var39    0.06023
25                       ind_var39    0.06023
26               num_op_var41_ult1  0.0601569
27                  num_var22_ult3  0.0595218
28                      num_var8_0  0.0589325
29                      ind_var8_0  0.0589325
..                             ...        ...
276                    ind_var24_0  0.0272674
277                    num_var24_0  0.0272674
278                ind_var13_corto  0.0272072
279                num_var13_corto  0.0272072
280                    ind_var13_0  0.0271101
281                    num_var13_0  0.0271101
282           num_var43_recib_ult1  0.0268937
283                      ind_var13  0.0266316
284                      num_var13  0.0266316
285                      ind_var24  0.0262164
286                      num_var24  0.0262164
287           num_meses_var12_ult3  0.0260948
288                    saldo_var13  0.0254184
289   saldo_medio_var13_corto_ult1   0.025376
290              saldo_var13_corto  0.0253253
291     num_meses_var13_corto_ult3  0.0250464
292                    saldo_var24    0.02502
293   saldo_medio_var13_corto_ult3  0.0249861
294      delta_num_aport_var13_1y3  0.0248737
295      delta_imp_aport_var13_1y3   0.024865
296          num_aport_var13_hace3   0.024816
297  saldo_medio_var13_corto_hace2  0.0243511
298        saldo_medio_var12_hace3  0.0243385
299  saldo_medio_var13_corto_hace3  0.0241678
300                num_var13_largo  0.0236216
301                ind_var13_largo  0.0236216
302              num_var13_largo_0  0.0236153
303              ind_var13_largo_0  0.0236153
304          imp_aport_var13_hace3  0.0232913
305              saldo_var13_largo  0.0229137

[306 rows x 2 columns]

### Generate feature combinations and their AUC

In [167]:
x_train[random.sample(list(x_train.columns),5)].reset_index(drop=True)

,var3,var15,imp_ent_var16_ult1,imp_op_var39_comer_ult1,imp_op_var39_comer_ult3,imp_op_var40_comer_ult1,imp_op_var40_comer_ult3,imp_op_var40_efect_ult1,imp_op_var40_efect_ult3,imp_op_var40_ult1,...,saldo_medio_var29_ult3,saldo_medio_var33_hace2,saldo_medio_var33_hace3,saldo_medio_var33_ult1,saldo_medio_var33_ult3,saldo_medio_var44_hace2,saldo_medio_var44_hace3,saldo_medio_var44_ult1,saldo_medio_var44_ult3,var38
34461,2,23,0,0.00,0.00,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,137767.920000
23065,2,23,0,0.00,0.00,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,261810.690000
71035,2,31,0,38.10,202.20,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,104074.260000
70755,2,29,0,0.00,0.00,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,117310.979016
69524,2,49,3,0.00,0.00,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,40082.940000
27585,2,23,0,0.00,0.00,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,118323.210000
55656,2,36,0,0.00,0.00,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,38024.250000
12398,2,44,0,0.00,0.00,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,117310.979016
34282,2,24,0,0.00,0.00,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,117310.979016
49888,2,23,0,96.60,96.60,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,69176.910000
49971,2,24,0,0.00,0.00,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,173818.410000
34365,2,54,3,0.00,0.00,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,66886.890000
53279,2,21,0,0.00,0.00,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,155047.110000
29130,2,23,0,462.09,656.46,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,117310.979016
38987,2,56,0,0.00,0.00,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,199009.110000
49238,2,23,0,0.00,0.00,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,187739.190000
63699,2,28,0,0.00,0.00,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,66454.920000
1393,2,23,0,0.00,0.00,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,50057.880000
53341,2,32,0,0.00,0.00,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,117310.979016
35144,2,23,0,0.00,0.00,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,117310.979016
1510,2,24,0,0.00,0.00,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,91074.900000
21301,2,24,0,0.00,0.00,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,93109.320000
4484,2,63,0,0.00,0.00,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,117310.979016
15510,2,25,0,0.00,0.00,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,46980.870000
40416,2,60,0,0.00,0.00,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,117310.979016
23978,2,26,0,0.00,0.00,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,50980.320000
20526,2,51,0,0.00,0.00,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,46170.300000
43697,2,23,0,0.00,0.00,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,137453.490000
20557,2,28,0,0.00,0.00,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,202374.300000
35228,2,25,0,179.82,179.82,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,105609.900000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
63697,139,63,0,0.00,0.00,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,117310.979016
61756,2,23,0,0.00,0.00,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,336129.870000
68097,2,74,0,0.00,0.00,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,82293.570000
3606,2,24,0,0.00,0.00,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,117310.979016
37183,2,23,0,0.00,2.97,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,99490.170000
33878,2,23,0,0.00,0.00,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,71240.760000
51040,2,23,0,0.00,0.00,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,117310.979016
44510,2,26,0,0.00,0.00,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,62399.310000
26103,2,23,0,0.00,0.00,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,117310.979016
17137,2,46,0,0.00,0.00,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,117310.979016
19433,2,54,0,0.00,0.00,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,117310.979016
31959,2,23,0,0.00,0.00,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,123878.820000
57245,2,33,0,0.00,0.00,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,101993.940000
19946,2,23,0,0.00,0.00,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,177376.140000
8444,2,44,0,60.00,60.00,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,113788.440000
64395,2,22,0,0.00,0.00,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,117310.979016
51668,0,47,0,0.00,0.00,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,78774.900000
35730,2,26,0,0.00,0.00,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,72000.420000
45413,2,37,0,715.02,962.64,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,25724.370000
21758,2,53,0,0.00,0.00,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,115132.170000
36230,2,74,0,0.00,0.00,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,117310.979016
31228,2,25,0,0.00,0.00,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,94335.060000
43757,2,27,0,0.00,0.00,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,87736.980000
7751,2,26,0,0.00,0.00,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,149155.650000
49100,2,34,0,0.00,0.00,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,160947.420000
20609,2,34,780,424.41,424.41,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,60588.180000
21440,2,27,0,0.00,29.94,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,117310.979016
73349,2,30,1845,0.00,0.00,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,639151.230000
50057,2,27,0,0.00,0.00,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,117310.979016
5192,2,36,0,353.85,480.75,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,89661.150000

In [190]:
x_train[random.sample(list(x_train.columns),5)].reset_index(drop=True).columns[0]

'imp_var43_emit_ult1'

In [191]:
num_combinations=5
total_no_iterations=1000
featuretable = pd.DataFrame(index=range(total_no_iterations),columns=['F1','F2','F3','F4','F5','AUC'])

for i in range(total_no_iterations):
    traininputfeature = x_train[random.sample(list(x_train.columns),num_combinations)].reset_index(drop=True)
    validinputfeature = x_valid[random.sample(list(x_valid.columns),num_combinations)].reset_index(drop=True)
    gbm_classifier.fit(traininputfeature,y_train)
    valid_auc = auc(y_valid,gbm_classifier.predict_proba(validinputfeature)[:,1],reorder=True)
    featuretable.ix[i,'F1'] = traininputfeature.columns[0]
    featuretable.ix[i,'F2'] = traininputfeature.columns[1]
    featuretable.ix[i,'F3'] = traininputfeature.columns[2]
    featuretable.ix[i,'F4'] = traininputfeature.columns[3]
    featuretable.ix[i,'F5'] = traininputfeature.columns[4]
    featuretable.ix[i,'AUC'] = valid_auc

In [192]:
featuretable

,F1,F2,F3,F4,F5,AUC
0,num_var12_0,saldo_medio_var13_medio_ult3,ind_var24,delta_imp_aport_var17_1y3,num_var39_0,0.0364202
1,saldo_var37,num_var31_0,ind_var20_0,saldo_medio_var29_ult3,num_var13,0.0403567
2,saldo_var24,imp_sal_var16_ult1,ind_var13,num_var45_ult3,num_med_var22_ult3,0.0333784
3,num_meses_var44_ult3,num_trasp_var33_in_hace3,num_var13_largo,saldo_medio_var33_hace3,ind_var31,0.0401844
4,saldo_medio_var33_ult1,saldo_var13_largo,num_var37,delta_num_aport_var17_1y3,ind_var20_0,0.0398718
5,num_var13_largo,imp_var7_recib_ult1,num_var45_ult1,num_var32,num_op_var40_hace2,0.0308338
6,num_var5,num_var34,num_var5_0,num_var45_ult1,imp_compra_var44_ult1,0.0695933
7,ind_var32,ind_var29_0,num_var42,num_var41_0,saldo_medio_var13_largo_ult1,0.0701644
8,delta_imp_amort_var18_1y3,delta_num_trasp_var33_in_1y3,ind_var14,num_meses_var29_ult3,ind_var39,0.0398736
9,num_var12,saldo_medio_var29_hace3,num_trasp_var17_in_ult1,num_meses_var17_ult3,ind_var5_0,0.044159
10,num_meses_var8_ult3,imp_amort_var18_ult1,num_op_var40_efect_ult1,saldo_var13_corto,delta_num_aport_var33_1y3,0.047835
11,delta_imp_aport_var13_1y3,saldo_medio_var44_ult1,ind_var7_emit_ult1,imp_reemb_var13_ult1,imp_var7_emit_ult1,0.0398616
12,saldo_var17,num_op_var39_hace2,num_var37,ind_var26,ind_var18,0.0441621
13,saldo_var14,imp_trasp_var17_out_ult1,num_meses_var44_ult3,num_var44,ind_var41_0,0.0418954
14,imp_aport_var17_hace3,ind_var7_emit_ult1,saldo_medio_var5_hace2,num_compra_var44_hace3,num_meses_var5_ult3,0.0579873
15,imp_aport_var33_hace3,ind_var43_recib_ult1,saldo_medio_var29_hace3,num_meses_var13_medio_ult3,num_op_var39_ult3,0.0415796
16,imp_op_var40_comer_ult3,saldo_var1,num_var33,ind_var20,num_meses_var29_ult3,0.0518
17,imp_op_var41_comer_ult1,ind_var34,saldo_medio_var5_ult1,num_op_var40_efect_ult1,delta_num_trasp_var33_in_1y3,0.0580386
18,saldo_medio_var13_largo_hace3,num_reemb_var17_ult1,imp_trasp_var33_in_ult1,num_trasp_var17_out_ult1,num_var37_med_ult2,0.0349881
19,imp_reemb_var17_ult1,num_var37_med_ult2,num_var32,num_ent_var16_ult1,saldo_medio_var13_corto_hace2,0.0406128
20,saldo_medio_var8_ult3,saldo_var44,num_var40_0,num_var18,imp_reemb_var13_ult1,0.0417921
21,imp_trasp_var33_in_hace3,saldo_medio_var12_hace2,saldo_var26,imp_op_var39_efect_ult1,ind_var41_0,0.0406989
22,imp_op_var40_efect_ult3,num_var29_0,ind_var29,ind_var26,num_aport_var33_ult1,0.0434999
23,num_compra_var44_hace3,ind_var39,num_var30_0,num_trasp_var17_in_hace3,ind_var40_0,0.0527689
24,num_med_var45_ult3,delta_num_reemb_var17_1y3,num_var44_0,saldo_medio_var5_ult1,ind_var9_cte_ult1,0.051037
25,saldo_medio_var33_ult3,num_var5,imp_trans_var37_ult1,num_reemb_var17_hace3,num_aport_var17_hace3,0.0461694
26,ind_var31,num_var1_0,ind_var29_0,num_var42,num_trasp_var33_in_hace3,0.0447522
27,num_var8,ind_var10_ult1,saldo_medio_var17_ult1,imp_aport_var33_ult1,saldo_medio_var8_hace3,0.0508498
28,num_var22_hace2,imp_aport_var13_hace3,num_var4,num_var41_0,imp_trans_var37_ult1,0.0916547
29,num_compra_var44_hace3,saldo_var14,ind_var26_cte,imp_amort_var34_ult1,num_op_var39_hace3,0.0479595
...,...,...,...,...,...,...
970,saldo_var20,num_var12,num_op_var41_efect_ult1,saldo_var31,saldo_medio_var17_hace3,0.0461848
971,num_meses_var17_ult3,ind_var39,ind_var32_cte,num_var13,var3,0.0460539
972,num_var20,imp_aport_var33_hace3,saldo_medio_var29_ult3,ind_var20,ind_var7_emit_ult1,0.0400163
973,saldo_medio_var8_hace2,saldo_var1,delta_num_reemb_var17_1y3,imp_var43_emit_ult1,saldo_var40,0.0433571
974,saldo_medio_var13_largo_ult3,saldo_medio_var12_hace2,num_compra_var44_hace3,num_op_var40_efect_ult3,imp_op_var41_ult1,0.0658073
975,delta_num_trasp_var17_in_1y3,ind_var30_0,num_var8_0,imp_var7_recib_ult1,num_var35,0.05558
976,num_meses_var44_ult3,saldo_medio_var44_ult1,delta_num_trasp_var33_in_1y3,imp_var7_recib_ult1,num_meses_var33_ult3,0.0400163
977,saldo_medio_var13_largo_hace3,saldo_medio_var13_corto_ult3,ind_var20,imp_trans_var37_ult1,num_var14_0,0.0365298
978,imp_var43_emit_ult1,num_ent_var16_ult1,imp_aport_var13_hace3,num_var20_0,imp_op_var41_comer_ult3,0.041579
979,saldo_medio_var29_ult1,saldo_var44,ind_var33,ind_var20_0,num_var35,0.0444426
980,num_op_var39_efect_ult1,imp_aport_var17_ult1,num_ent_var16_ult1,imp_op_var41_comer_ult3,num_var31,0.0453039
981,saldo_medio_var17_ult3,saldo_medio_var44_hace2,num_reemb_var17_hace3,saldo_medio_var8_ult1,saldo_medio_var29_ult3,0.0421384
982,ind_var31,num_var1,imp_aport_var33_hace3,num_var31_0,num_var12,0.0438778
983,ind_var25_cte,saldo_var5,num_trasp_var33_in_ult1,saldo_var12,delta_num_trasp_var33_in_1y3,0.0574923
984,saldo_medio_var8_ult3,ind_var13_corto,saldo_var37,num_aport_var13_ult1,saldo_var33,0.0392816
985,var15,imp_op_var39_efect_ult1,num_var22_hace3,saldo_medio_var13_corto_hace2,ind_var10_ult1,0.0704993
986,var3,ind_var26,num_var13_largo,ind_var32_cte,ind_var8_0,0.0760253
987,saldo_medio_var13_medio_ult1,num_venta_var44_hace3,ind_var31,ind_var32,num_op_var39_efect_ult3,0.0509268
988,delta_num_trasp_var33_out_1y3,num_ent_var16_ult1,num_var18,num_op_var41_efect_ult1,num_op_var39_efect_ult3,0.0498482
989,num_aport_var13_hace3,delta_imp_aport_var33_1y3,saldo_medio_var17_hace2,ind_var13_largo,ind_var17,0.0335143
990,num_var40_0,saldo_medio_var12_ult3,num_var35,ind_var18,num_var8,0.0524253
991,var3,num_op_var40_ult1,saldo_var32,imp_op_var39_efect_ult1,saldo_medio_var44_ult3,0.0480572
992,imp_reemb_var13_ult1,delta_num_venta_var44_1y3,num_var22_hace2,num_var43_recib_ult1,num_reemb_var33_ult1,0.0380777
993,saldo_var44,imp_compra_var44_ult1,imp_aport_var13_ult1,num_med_var45_ult3,num_var17,0.0352265
994,num_var13,delta_imp_aport_var17_1y3,saldo_var8,ind_var33_0,num_meses_var5_ult3,0.0523282
995,num_var13,saldo_var17,num_var43_emit_ult1,num_var1,ind_var13,0.0492873
996,num_var45_hace2,ind_var5,num_var41_0,ind_var37,num_var44_0,0.0325788
997,num_var13_corto_0,saldo_medio_var29_hace3,ind_var18,num_op_var39_hace3,num_var17_0,0.0329753
998,saldo_var42,num_var32,delta_num_aport_var17_1y3,saldo_medio_var33_ult3,imp_op_var39_comer_ult1,0.0573302
999,ind_var30_0,num_op_var39_ult1,num_var37,saldo_var30,num_meses_var13_medio_ult3,0.067786